run:
  timeout: 5m

  build-tags:
    - e2e

linters:
  enable:
    - asciicheck
    - errorlint
    - gosec
    - prealloc
    - revive
    - stylecheck
    - tparallel
    - unconvert
    - unparam
  disable:
    - errcheck

issues:
  include:
    # Disable excluding issues about comments from golint.
    - EXC0002

  exclude-rules:
    - path: test # Excludes /test, *_test.go etc.
      linters:
        - gosec
        - unparam

    # Ignore "context.Context should be the first parameter of a function" errors in tests.
    # See: https://github.com/golang/lint/issues/422
    - path: test
      text: "context.Context should be the first"
      linters:
        - revive

    # Allow source and sink receivers in conversion code for clarity.
    - path: _conversion\.go
      text: "ST1016:"
      linters:
        - stylecheck
    - path: _conversion\.go
      text: "receiver name"
      linters:
        - revive

    # This check has quite a few false positives where there isn't much value in the package comment.
    - text: "ST1000: at least one file in a package should have a package comment"
      linters:
        - stylecheck

  exclude-dirs:
    - pkg/client

  exclude-files:
    - prom.png

